name = "repkg"
version = "0.1.0"

[build]
command = ["cargo", "build", "--release"]

[build.dependencies]
cargo = "1.0.0"

[[bin]]
path = "target/release/repkg-build.exe"

[[bin]]
path = "target/release/repkg.exe"

[[bin]]
path = "target/release/repkg-registry-host.exe"

[[lib]]
path = "target/release/librepkg_core.rlib"