[package]
name = "repkg-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = { workspace = true }
thiserror = { workspace = true }
lenient_semver = { workspace = true }
semver = { workspace = true }